version: "3.8"
services:
  api:
    build:
      context: .
    ports:
      - "5277:8080"  # Map API container port 80 to localhost:5277
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=YourDb;Username=postgres;Password=postgres
    depends_on:
      - postgres
    networks:
      - app-network


  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./Client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "start", "--", "--host", "0.0.0.0"]
    networks:
      - app-network

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=YourDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
